"""Pull the player profile through the RoyaleAPI proxy (the API key is IP-locked to the
proxy's 45.79.218.79) and write data/clash.js plus small card images for the Side Quests
console. Nothing is rewritten unless the trophies or the deck actually changed."""
import io
import json
import os
import re
import sys
import urllib.parse
import urllib.request
from datetime import date
from pathlib import Path

from PIL import Image

KEY, TAG = os.environ.get('CR_API_KEY'), os.environ.get('CR_PLAYER_TAG')
if not KEY or not TAG:
    sys.exit('CR_API_KEY and CR_PLAYER_TAG are required')

DATA_FILE = Path('data/clash.js')
CARD_DIR = Path('data/cr')


def get(url, headers=None):
    req = urllib.request.Request(url, headers={'User-Agent': 'quamos.dev clash sync', **(headers or {})})
    with urllib.request.urlopen(req, timeout=30) as res:
        return res.read()


def slug(name):
    return re.sub(r'[^a-z0-9]+', '-', name.lower()).strip('-')


p = json.loads(get(f'https://proxy.royaleapi.dev/v1/players/{urllib.parse.quote(TAG)}',
                   {'Authorization': f'Bearer {KEY}'}))

# the API reports card levels relative to each rarity; shift them onto the in-game scale
top_level = max(c['maxLevel'] for c in p['cards'])
deck, sources = [], {}
for c in p['currentDeck']:
    evolved = c.get('evolutionLevel', 0) > 0
    img = f"{slug(c['name'])}{'-evo' if evolved else ''}.webp"
    sources[img] = (c['iconUrls'].get('evolutionMedium') if evolved else None) or c['iconUrls']['medium']
    deck.append({
        'name': c['name'],
        'rarity': c['rarity'],
        'elixir': c.get('elixirCost'),
        'level': c['level'] + top_level - c['maxLevel'],
        'evolved': evolved,
        'img': img,
    })

player = {
    'name': p['name'],
    'tag': p['tag'],
    'trophies': p['trophies'],
    'bestTrophies': p['bestTrophies'],
    'arena': (p.get('arena') or {}).get('name'),
    'deck': deck,
}

previous = None
if DATA_FILE.exists():
    previous = json.loads(DATA_FILE.read_text().split('=', 1)[1].strip().rstrip(';'))['player']
if previous == player:
    print('unchanged')
    sys.exit(0)

# card art: 300px PNGs from Supercell's CDN become ~8KB WebPs
CARD_DIR.mkdir(parents=True, exist_ok=True)
for img, url in sources.items():
    if not (CARD_DIR / img).exists():
        im = Image.open(io.BytesIO(get(url))).convert('RGBA')
        im.thumbnail((150, 180), Image.LANCZOS)
        im.save(CARD_DIR / img, 'WEBP', quality=82, method=6)
for stale in CARD_DIR.glob('*.webp'):
    if stale.name not in sources:
        stale.unlink()

data = {'synced': date.today().isoformat(), 'player': player}
DATA_FILE.write_text('// generated by .github/workflows/clash-data.yml — do not edit by hand\n'
                     f'window.CLASH_DATA = {json.dumps(data, indent=2, ensure_ascii=False)};\n')
print(f"synced: {player['trophies']} trophies, deck: {', '.join(c['name'] for c in deck)}")
